### ISSUE TITLE
:hammer: Clone repository job

### ISSUE THREAD

**Issue by Thomaltarix** [Epitech-Project/My_Marvin#10]
# :white_check_mark: What's needed
This job has many little subtasks to be done. Each task is independent.

## 📋 Subtasks
- [x] Named `clone-repository`.
- [x] It is in `Tools` folder.
- [x] Has a `GIT_REPOSITORY_URL` string parameter with a `Git URL of the repository to clone` description and no default value.
- [x] When executed, clone with Git the repository at the specified URL, using a single shell command.
- [x] Performs a pre-build workspace cleanup. *(https://plugins.jenkins.io/ws-cleanup/)*
- [x] Is only executed manually.
