### ISSUE TITLE
:hammer: Create the SEED job

### ISSUE THREAD

**Issue by Thomaltarix** [Epitech-Project/My_Marvin#11]
# :white_check_mark: What's needed
The Seed job is split into 5 parts that has to be done.

## 📋 Subtasks
- [x] Is named `SEED`.
- [x] Is in `Tools` folder.
- [x] Is only executed manually.
- [x] **When executed**, create a job with the specifications listed here #12 , using a single job_dsl.groovy file script execution.
- [x] Has two string parameters:
- `GITHUB_NAME` with a `GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")` description
- `DISPLAY_NAME` with a `Display name for the job` description
