### ISSUE TITLE
:hammer: Setup Jobs created by the Seed job

### ISSUE THREAD

**Issue by Thomaltarix** [Epitech-Project/My_Marvin#12]
# :white_check_mark: What's needed
The following specifications must be applied to all the jobs that are created by the SEED job https://github.com/6im0n/My_Marvin/issues/11.

## 📋 Subtasks
- [x] Are in the root.
- [x] Are named according to the `DISPLAY_NAME` parameter.
- [x] Have a GitHub project property pointing at the repository specified by the value of the `GITHUB_NAME` parameter.
- [x] Have no parameters.
- [x] Use the prebuilt `Git SCM system` to automatically get the GitHub repository given by the value of the `GITHUB_NAME` parameter.
- [x] Perform a pre-build workspace cleanup. *(https://plugins.jenkins.io/ws-cleanup/)*
- [x] Are only executed either by:
– a SCM poll triggered every minute *(which starts a build if there are changes since the last one)*
– manual trigger.
---
- [x] When executed, launch each of the following commands in separate shell script steps:
– `make fclean`
– `make`
– `make tests_run`
– `make clean`

*You can setup both the GitHub project URL and the Git SCM URL with a single instruction using the `GITHUB_NAME` parameter, simplify your job by trying to find it!*
*A root element is an element visible on the home page’s dashboard.*
