### ISSUE TITLE
:globe_with_meridians: global configuration

### ISSUE THREAD

**Issue by 6im0n** [Epitech-Project/My_Marvin#3]
# :white_check_mark: What's needed
The configuration file got 3 main parts and a little one.
The little one is easier than the 3 others but must be done.

## 📋 Subtasks
- [x] Configure jenkins system message to `Welcome to the Chocolatine-Powered Marvin Jenkins Instance.`
- [x] Setup all the users #5 
- [x] Setup the authorization strategy *(The User part is mandatory to do this one)* #6
