### ISSUE TITLE
:passport_control: Authorization strategy

### ISSUE THREAD

**Issue by 6im0n** [Epitech-Project/My_Marvin#6]
# :white_check_mark: What's needed
### Authorization strategy :
Enables user authorization using a Role-Based strategy

## 📋 Subtasks
- [x]  Strategy must be role-based.
---
- [x] A global role` Admin `
Description: a “Marvin master” 
Permissions: Has all the permissions;
Assigned to Hugo
---
- [x]  A global role named `ape` 
Description: “Pedagogical team member”
Permissions: Can build a job and see their workspaces
Assigned to Jeremy.
---
- [x]  A global role named `gorilla` 
Description : “Group Obsessively Researching Innovation Linked to Learning and Accomplishment”
Permissions: same permissions as the ape role
* the ability to create, configure, delete and move a job,
* cancel builds;
Assigned to Garance.
---
- [x] A global role named `assist`
Description: “Assistant”
Permission: can only view jobs and their workspaces
Is assigned to Nassim

## :bulb: Infos:
- The specified permissions are the only ones to grant, any non-specified permission
must not be given (unless it is inherently needed).
- The specified roles are the only ones to define, no other role than those can be
defined.
