### ISSUE TITLE
:hammer: Create jenkins Jobs

### ISSUE THREAD

**Issue by Thomaltarix** [Epitech-Project/My_Marvin#7]
# :white_check_mark: What's needed
The jobs section of the project is split in 2 main parts.

## 📋 Subtasks
- [x] Create the `Tools` folder with the `Folder for miscellaneous tools.` description at the root
- [x] The Clone repository job https://github.com/6im0n/My_Marvin/issues/10
- [x] The SEED job #11 *(required the `Tools` folder)*
